allowForkPRs: true

config: |
  automerge: true

dataStorage: 5Gi

environment: null

gitlab:
  token: glpat-dxrS2Sy712JE3ygu3pUh
  hostname: http://gitlab.local
  secret: a928d6c2
  user: atlantis

ingress:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  enabled: true
  host: atlantis.kustomize.local
  ingressClassName: traefik
  path: /

logLevel: debug

orgAllowlist: gitlab.local/*

repoConfig: |
  ---
  repos:
  - id: /.*/
    allowed_overrides: [apply_requirements]

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 1Gi

service:
  port: 80
  type: ClusterIP
