apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

helmCharts:
  - name: atlantis
    repo: https://runatlantis.github.io/helm-charts
    version: 4.14.0
    releaseName: atlantis
    namespace: atlantis
    valuesFile: helm_values.yaml

resources:
  - "./resources/namespace.yaml"
