apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

resources:
  - ../../base

replicas:
  - name: atlantis
    count: 1

generatorOptions:
  disableNameSuffixHash: false
